# Translations template for neutron.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the neutron project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: neutron 2015.1.dev362.g9b1cda6\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-11-20 06:08+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: neutron/policy.py:129
#, python-format
msgid ""
"Backward compatibility unavailable for deprecated policy %s. The policy "
"will not be enforced"
msgstr ""

#: neutron/policy.py:317
#, python-format
msgid "Policy check error while calling %s!"
msgstr ""

#: neutron/agent/dhcp_agent.py:147
#, python-format
msgid "Unable to %(action)s dhcp for %(net_id)s."
msgstr ""

#: neutron/agent/dhcp_agent.py:174
#, python-format
msgid "Unable to sync network state on deleted network %s"
msgstr ""

#: neutron/agent/dhcp_agent.py:187
msgid "Unable to sync network state."
msgstr ""

#: neutron/agent/dhcp_agent.py:218
#, python-format
msgid "Network %s info call failed."
msgstr ""

#: neutron/agent/dhcp_agent.py:591 neutron/agent/l3_agent.py:2006
#: neutron/agent/metadata/agent.py:416
#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:277
msgid "Failed reporting state!"
msgstr ""

#: neutron/agent/l3_agent.py:507 neutron/tests/unit/test_l3_agent.py:1974
#, python-format
msgid "Error importing interface driver '%s'"
msgstr ""

#: neutron/agent/l3_agent.py:579 neutron/agent/linux/dhcp.py:792
msgid "An interface driver must be specified"
msgstr ""

#: neutron/agent/l3_agent.py:584
msgid "Router id is required if not using namespaces."
msgstr ""

#: neutron/agent/l3_agent.py:602
msgid "RuntimeError in obtaining router list for namespace cleanup."
msgstr ""

#: neutron/agent/l3_agent.py:637
#, python-format
msgid "Failed to destroy stale router namespace %s"
msgstr ""

#: neutron/agent/l3_agent.py:653 neutron/agent/linux/dhcp.py:238
#, python-format
msgid "Failed trying to delete namespace: %s"
msgstr ""

#: neutron/agent/l3_agent.py:855
#, python-format
msgid "Ignoring multiple IPs on router port %s"
msgstr ""

#: neutron/agent/l3_agent.py:1206
#, python-format
msgid "Failed sending gratuitous ARP: %s"
msgstr ""

#: neutron/agent/l3_agent.py:1271
msgid "DVR: no map match_port found!"
msgstr ""

#: neutron/agent/l3_agent.py:1475
msgid "DVR: error adding redirection logic"
msgstr ""

#: neutron/agent/l3_agent.py:1487
msgid "DVR: removed snat failed"
msgstr ""

#: neutron/agent/l3_agent.py:1588
msgid "Missing subnet/agent_gateway_port"
msgstr ""

#: neutron/agent/l3_agent.py:1729
msgid "DVR: Failed updating arp entry"
msgstr ""

#: neutron/agent/l3_agent.py:1778
#, python-format
msgid "The external network bridge '%s' does not exist"
msgstr ""

#: neutron/agent/l3_agent.py:1818
#, python-format
msgid "Failed to fetch router information for '%s'"
msgstr ""

#: neutron/agent/l3_agent.py:1836
#, python-format
msgid "Removing incompatible router '%s'"
msgstr ""

#: neutron/agent/l3_agent.py:1887
msgid "Failed synchronizing routers due to RPC error"
msgstr ""

#: neutron/agent/l3_agent.py:1890
msgid "Failed synchronizing routers"
msgstr ""

#: neutron/agent/l3_ha_agent.py:136
#, python-format
msgid "Unable to process HA router %s without ha port"
msgstr ""

#: neutron/agent/netns_cleanup_util.py:141
#, python-format
msgid "Error unable to destroy namespace: %s"
msgstr ""

#: neutron/agent/linux/async_process.py:164
#, python-format
msgid "An error occurred while killing [%s]."
msgstr ""

#: neutron/agent/linux/async_process.py:186
#, python-format
msgid "An error occurred while communicating with async process [%s]."
msgstr ""

#: neutron/agent/linux/daemon.py:36
#, python-format
msgid "Error while handling pidfile: %s"
msgstr ""

#: neutron/agent/linux/daemon.py:93
msgid "Fork failed"
msgstr ""

#: neutron/agent/linux/daemon.py:135
#, python-format
msgid "Pidfile %s already exist. Daemon already running?"
msgstr ""

#: neutron/agent/linux/dhcp.py:329
#, python-format
msgid ""
"FAILED VERSION REQUIREMENT FOR DNSMASQ. DHCP AGENT MAY NOT RUN CORRECTLY!"
" Please ensure that its version is %s or above!"
msgstr ""

#: neutron/agent/linux/dhcp.py:335
#, python-format
msgid ""
"Unable to determine dnsmasq version. Please ensure that its version is %s"
" or above!"
msgstr ""

#: neutron/agent/linux/dhcp.py:798
#, python-format
msgid "Error importing interface driver '%(driver)s': %(inner)s"
msgstr ""

#: neutron/agent/linux/external_process.py:227
#, python-format
msgid ""
"%(service)s for %(resource_type)s with uuid %(uuid)s not found. The "
"process should not have died"
msgstr ""

#: neutron/agent/linux/external_process.py:247
#, python-format
msgid "respawning %(service)s for uuid %(uuid)s"
msgstr ""

#: neutron/agent/linux/external_process.py:253
msgid "Exiting agent as programmed in check_child_processes_actions"
msgstr ""

#: neutron/agent/linux/interface.py:154
#, python-format
msgid "Failed deleting ingress connection state of floatingip %s"
msgstr ""

#: neutron/agent/linux/interface.py:163
#, python-format
msgid "Failed deleting egress connection state of floatingip %s"
msgstr ""

#: neutron/agent/linux/interface.py:285 neutron/agent/linux/interface.py:330
#: neutron/agent/linux/interface.py:397 neutron/agent/linux/interface.py:439
#, python-format
msgid "Failed unplugging interface '%s'"
msgstr ""

#: neutron/agent/linux/ip_link_support.py:107
msgid "Failed executing ip command"
msgstr ""

#: neutron/agent/linux/iptables_manager.py:446
#, python-format
msgid ""
"IPTablesManager.apply failed to apply the following set of iptables "
"rules:\n"
"%s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:73 neutron/agent/linux/ovs_lib.py:171
#: neutron/agent/linux/ovs_lib.py:292
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:243
msgid ""
"Unable to create VXLAN tunnel port. Please ensure that an openvswitch "
"version that supports VXLAN is installed."
msgstr ""

#: neutron/agent/linux/ovs_lib.py:523
#, python-format
msgid "OVS flows could not be applied on bridge %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:533
#, python-format
msgid "Interface %s not found."
msgstr ""

#: neutron/agent/linux/ovs_lib.py:544
#, python-format
msgid "Unable to retrieve bridges. Exception: %s"
msgstr ""

#: neutron/agent/linux/ovs_lib.py:553
#, python-format
msgid "Bridge %s not found."
msgstr ""

#: neutron/agent/linux/ovsdb_monitor.py:51
#, python-format
msgid "Error received from ovsdb monitor: %s"
msgstr ""

#: neutron/agent/metadata/agent.py:156
#: neutron/agent/metadata/namespace_proxy.py:75
msgid "Unexpected error."
msgstr ""

#: neutron/api/extensions.py:483
#, python-format
msgid "Error fetching extended attributes for extension '%s'"
msgstr ""

#: neutron/api/extensions.py:492
#, python-format
msgid ""
"It was impossible to process the following extensions: %s because of "
"missing requirements."
msgstr ""

#: neutron/api/extensions.py:509
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: neutron/api/extensions.py:527
#, python-format
msgid "Extension path '%s' doesn't exist!"
msgstr ""

#: neutron/api/rpc/agentnotifiers/dhcp_rpc_agent_api.py:91
#, python-format
msgid ""
"Will not send event %(method)s for network %(net_id)s: no agent "
"available. Payload: %(payload)s"
msgstr ""

#: neutron/api/rpc/agentnotifiers/l3_rpc_agent_api.py:106
#, python-format
msgid ""
"No plugin for L3 routing registered. Cannot notify agents with the "
"message %s"
msgstr ""

#: neutron/api/rpc/handlers/l3_rpc.py:71
msgid ""
"No plugin for L3 routing registered! Will reply to l3 agent with empty "
"router dictionary."
msgstr ""

#: neutron/api/v2/base.py:364
#, python-format
msgid "Unable to undo add for %(resource)s %(id)s"
msgstr ""

#: neutron/api/v2/resource.py:97 neutron/api/v2/resource.py:105
#: neutron/api/v2/resource.py:125
#, python-format
msgid "%s failed"
msgstr ""

#: neutron/cmd/sanity_check.py:41
msgid ""
"Check for Open vSwitch VXLAN support failed. Please ensure that the "
"version of openvswitch being used has VXLAN support."
msgstr ""

#: neutron/cmd/sanity_check.py:50
msgid ""
"Check for Open vSwitch patch port support failed. Please ensure that the "
"version of openvswitch being used has patch port support or disable "
"features requiring patch ports (gre/vxlan, etc.)."
msgstr ""

#: neutron/cmd/sanity_check.py:60
msgid ""
"Nova notifications are enabled, but novaclient is not installed. Either "
"disable nova notifications or install python-novaclient."
msgstr ""

#: neutron/cmd/sanity_check.py:70
msgid ""
"Check for Open vSwitch ARP responder support failed. Please ensure that "
"the version of openvswitch being used has ARP flows support."
msgstr ""

#: neutron/cmd/sanity_check.py:80
msgid ""
"Check for VF management support failed. Please ensure that the version of"
" ip link being used has VF support."
msgstr ""

#: neutron/cmd/sanity/checks.py:74
#, python-format
msgid "Unexpected exception while checking supported feature via command: %s"
msgstr ""

#: neutron/cmd/sanity/checks.py:106
msgid "Unexpected exception while checking supported ip link command"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:152
#, python-format
msgid "Unable to generate mac address after %s attempts"
msgstr ""

#: neutron/db/db_base_plugin_v2.py:895
#, python-format
msgid "An exception occurred while creating the %(resource)s:%(item)s"
msgstr ""

#: neutron/db/dvr_mac_db.py:97
#, python-format
msgid "MAC generation error after %s attempts"
msgstr ""

#: neutron/db/dvr_mac_db.py:169
#, python-format
msgid "Could not retrieve gateway port for subnet %s"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:141
#, python-format
msgid "Failed to reschedule router %s"
msgstr ""

#: neutron/db/l3_agentschedulers_db.py:146
msgid "Exception encountered during router rescheduling."
msgstr ""

#: neutron/db/metering/metering_rpc.py:45
#, python-format
msgid "Unable to find agent %s."
msgstr ""

#: neutron/extensions/l3agentscheduler.py:49
#: neutron/extensions/l3agentscheduler.py:92
msgid "No plugin for L3 routing registered to handle router scheduling"
msgstr ""

#: neutron/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: neutron/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: neutron/openstack/common/lockutils.py:117
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: neutron/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: neutron/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: neutron/openstack/common/periodic_task.py:202
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: neutron/openstack/common/policy.py:535
#: neutron/openstack/common/policy.py:815
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: neutron/openstack/common/policy.py:545
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: neutron/openstack/common/service.py:269
msgid "Unhandled exception"
msgstr ""

#: neutron/plugins/cisco/models/virt_phy_sw_v2.py:279
#, python-format
msgid "Unable to delete port '%(pname)s' on switch. Exception: %(exp)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_gre.py:86
#, python-format
msgid "Skipping unreasonable gre ID range %(tun_min)s:%(tun_max)s"
msgstr ""

#: neutron/plugins/ml2/drivers/type_vxlan.py:92
#, python-format
msgid "Skipping unreasonable VXLAN VNI range %(tun_min)s:%(tun_max)s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:110
msgid "APIC service agent: failed in reporting state"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:205
#, python-format
msgid "No such interface (ignored): %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:255
msgid "APIC service agent: exception in LLDP parsing"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:310
#, python-format
msgid "APIC service agent: can not get MACaddr for %s"
msgstr ""

#: neutron/plugins/ml2/drivers/cisco/apic/apic_topology.py:326
msgid "APIC host agent: failed in reporting state"
msgstr ""

#: neutron/plugins/mlnx/agent/eswitch_neutron_agent.py:386
msgid "Error in agent event loop"
msgstr ""

#: neutron/plugins/nuage/syncmanager.py:55
#, python-format
msgid "Cannot complete the sync between Neutron and VSD because of error:%s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:101
msgid "Agent terminated!: Failed to get a datapath."
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:120
msgid "Agent terminated"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:157
msgid "Agent failed to create agent config map"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:443
#, python-format
msgid "No local VLAN available for net-id=%s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:458
#, python-format
msgid ""
"Cannot provision %(network_type)s network for net-id=%(net_uuid)s - "
"tunneling disabled"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:469
#, python-format
msgid ""
"Cannot provision %(network_type)s network for net-id=%(net_uuid)s - no "
"bridge for physical_network %(physical_network)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:479
#, python-format
msgid ""
"Cannot provision unknown network type %(network_type)s for net-"
"id=%(net_uuid)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:517
#, python-format
msgid ""
"Cannot reclaim unknown network type %(network_type)s for net-"
"id=%(net_uuid)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:659
msgid "ofport should have a value that can be interpreted as an integer"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:662
#, python-format
msgid "Failed to set-up %(type)s tunnel port to %(ip)s"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:840
msgid "Error while synchronizing tunnels"
msgstr ""

#: neutron/plugins/ofagent/agent/ofa_neutron_agent.py:880
msgid "Error while processing VIF ports"
msgstr ""

#: neutron/plugins/openvswitch/agent/ovs_dvr_neutron_agent.py:159
msgid ""
"DVR: Failed to obtain a valid local DVR MAC address - L2 Agent operating "
"in Non-DVR Mode"
msgstr ""

#: neutron/plugins/vmware/plugins/base.py:2106
#, python-format
msgid ""
"Rolling back database changes for gateway device %s because of an error "
"in the NSX backend"
msgstr ""

#: neutron/scheduler/l3_agent_scheduler.py:285
#, python-format
msgid "Not enough candidates, a HA router needs at least %s agents"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_csr_rest_client.py:124
#, python-format
msgid "%(method)s: Unable to connect to CSR(%(host)s)"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_csr_rest_client.py:129
#, python-format
msgid "%(method)s: Unexpected error for CSR (%(host)s): %(error)s"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_csr_rest_client.py:159
#, python-format
msgid "Failed authentication with CSR %(host)s [%(status)s]"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_csr_rest_client.py:194
#, python-format
msgid "%(method)s: Request timeout for CSR(%(host)s)"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_ipsec.py:621
#, python-format
msgid "Unable to create %(resource)s %(which)s: %(status)d"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_ipsec.py:634
#: neutron/services/vpn/device_drivers/cisco_ipsec.py:662
#, python-format
msgid "Internal error - '%s' is not defined"
msgstr ""

#: neutron/services/vpn/device_drivers/cisco_ipsec.py:741
#, python-format
msgid "Unable to change %(tunnel)s admin state to %(state)s"
msgstr ""

#: neutron/services/vpn/device_drivers/ipsec.py:248
#, python-format
msgid "Failed to enable vpn process on router %s"
msgstr ""

#: neutron/services/vpn/device_drivers/ipsec.py:259
#, python-format
msgid "Failed to disable vpn process on router %s"
msgstr ""

